os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - docker pull hurrhnn/twrp-builder:latest
script:
  - mkdir ${HOME}/twrp
  - |
    sudo docker run --privileged --rm -i -v "${HOME}/twrp:/home/builder/twrp:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" hurrhnn/twrp-builder bash << EOF
    cd /home/builder/twrp/
    git clone https://github.com/MacBookPro34-comma-7/android_device_samsung_jackpotveltedcm.git device/samsung/jackpotveltedcm
    export ALLOW_MISSING_DEPENDENCIES=true
    source build/envsetup.sh
    lunch omni_jackpotveltedcm-eng
    make -j$(nproc --all) recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/jackpotveltedcm/recovery.img $HOME/twrp/TWRP-$version-jackpotveltedcm-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: true # Set "true" to deploy only on successful tagged commit builds
    repo: MacBookPro34-comma-7/android_device_samsung_jackpotveltedcm # Optional: If you want to deploy on different repository
    branch: TWRP # Optional: Needs to be exact as the config branch
branches:
  only:
    - TWRP # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
